BIN := self-dump
SRC := $(BIN).c

# Lib musl directories per architecture
X86_64_MUSL	:= ~/popcorn-compiler/lib/musl-1.1.18/toolchain_x86-64
ARM64_MUSL  := ~/popcorn-compiler/lib/musl-1.1.18/toolchain_aarch64

include ../common/common.mk
