BIN := ua-mod

SRC := ua.c adapt.c diffuse.c move.c setup.c c_timers.c print_results.c \
	 randdp.c c_print_results.c wtime.c verify.c convect.c mason.c precond.c \
	 transfer.c utils.c

#LLVM_TOOLCHAIN = ~/llvm-9-align/toolchain/bin
LLVM_TOOLCHAIN = ~/llvm-9-vanilla/toolchain/bin

#MUSL_TOOLCHAIN = ~/musl-toolchains/llvm-9-align
MUSL_TOOLCHAIN = ~/musl-toolchains/llvm-9-vanilla

include ../../common/common.mk
