BIN := bubble_sort
SRC := $(BIN).c

# Lib musl directories per architecture
X86_64_MUSL	:= ~/musl-toolchains/llvm-9/x86-64
ARM64_MUSL  := ~/musl-toolchains/llvm-9/aarch64

include ../common/common.mk
