BIN := bt

SRC := bt.c c_timers.c c_print_results.c wtime.c add.c adi.c error.c \
	 exact_rhs.c exact_solution.c initialize.c rhs.c set_constants.c \
	 solve_subs.c verify.c x_solve.c y_solve.c z_solve.c print_results.c

include ../common/common.mk
