BIN := ua

SRC := ua.c adapt.c diffuse.c move.c setup.c c_timers.c print_results.c \
	 randdp.c c_print_results.c wtime.c verify.c convect.c mason.c precond.c \
	 transfer.c utils.c

include ../common/common.mk
