BIN := ft

SRC := appft.c auxfnct.c fft3d.c mainft.c verify.c c_timers.c \
	 print_results.c randdp.c c_print_results.c wtime.c

INC_DIR := ../common/

PROJECT_DIR := ../../..

include ../../common/common.mk
