BIN := self-dump
SRC := $(BIN).c

# Lib musl directories per architecture
X86_64_MUSL	:= ~/musl_toolchains/musl_popcorn_toolchain_reloc/toolchain_x86-64
ARM64_MUSL  := ~/musl_toolchains/musl_popcorn_toolchain_reloc/toolchain_aarch64

include ../common/common.mk
