BIN := ep

SRC := ep.c c_timers.c print_results.c \
	 randdp.c c_print_results.c wtime.c

LLVM_TOOLCHAIN := ~/llvm-9/toolchain/bin
MUSL_TOOLCHAIN := ~/musl-toolchains/llvm-9

include ../../common/common.mk
