BIN := sp

SRC := sp.c add.c adi.c error.c exact_rhs.c c_timers.c print_results.c \
	 exact_solution.c initialize.c ninvr.c pinvr.c rhs.c set_constants.c \
	 txinvr.c tzetar.c verify.c x_solve.c y_solve.c z_solve.c \
	 randdp.c c_print_results.c wtime.c

PROJECT_DIR := ../../..

include ../../common/common.mk
