BIN := lu

SRC := blts.c buts.c domain.c erhs.c error.c exact.c c_timers.c \
	 jacld.c jacu.c l2norm.c lu.c pintgr.c read_input.c rhs.c setbv.c \
	 setcoeff.c setiv.c ssor.c verify.c print_results.c randdp.c \
	 c_print_results.c wtime.c

PROJECT_DIR := ../../..

include ../../common/common.mk
